  const x= document.getElementById("Js");
  setTimeout(() => {x.innerHTML= "Yeah"}, 1125);
  setTimeout(() => {x.innerHTML= "Yeah"}, 2250);
  setTimeout(() => {x.innerHTML= "Ối"}, 2750);
  setTimeout(() => {x.innerHTML= "dồi"}, 3000);
  setTimeout(() => {x.innerHTML= "ôi"}, 3250);
  setTimeout(() => {x.innerHTML= "Ối"}, 3750);
  setTimeout(() => {x.innerHTML= "dồi"}, 4000);
  setTimeout(() => {x.innerHTML= "ôi"}, 4250);
  setTimeout(() => {x.innerHTML= "Trình"}, 4750);
  setTimeout(() => {x.innerHTML= "là"}, 5000);
  setTimeout(() => {x.innerHTML= "gì"}, 5250);
  setTimeout(() => {x.innerHTML= "mà là"}, 5500);
  setTimeout(() => {x.innerHTML= "trình"}, 5750);
  setTimeout(() => {x.innerHTML= "ai"}, 6000);
  setTimeout(() => {x.innerHTML= "chấm"}, 6250);
  setTimeout(() => {x.innerHTML= "Anh"}, 6750);
  setTimeout(() => {x.innerHTML= "chỉ"}, 7000);
  setTimeout(() => {x.innerHTML= "biết"}, 7250);
  setTimeout(() => {x.innerHTML= "làm ba"}, 7500);
  setTimeout(() => {x.innerHTML= "mẹ"}, 7750);
  setTimeout(() => {x.innerHTML= "tự"}, 8000);
  setTimeout(() => {x.innerHTML= "hào"}, 8250);
  setTimeout(() => {x.innerHTML= "Xây căn"}, 8500);
  setTimeout(() => {x.innerHTML= "nhà"}, 8750);
  setTimeout(() => {x.innerHTML= "thật"}, 9000);
  setTimeout(() => {x.innerHTML= "to"}, 9250);
  setTimeout(() => {x.innerHTML= "ở một"}, 9500);
  setTimeout(() => {x.innerHTML= "mình"}, 9750);
  setTimeout(() => {x.innerHTML= "hai"}, 10000);
  setTimeout(() => {x.innerHTML= "tấm"}, 10250);
  setTimeout(() => {x.innerHTML= "Ối"}, 10750);
  setTimeout(() => {x.innerHTML= "dồi"}, 11000);
  setTimeout(() => {x.innerHTML= "ôi"}, 11250);
  setTimeout(() => {x.innerHTML= "Ối"}, 11750);
  setTimeout(() => {x.innerHTML= "dồi"}, 12000);
  setTimeout(() => {x.innerHTML= "ôi"}, 12250);
  setTimeout(() => {x.innerHTML= "Cứ lên"}, 12500);
  setTimeout(() => {x.innerHTML= "mạng"}, 12750);
  setTimeout(() => {x.innerHTML= "phán"}, 13000);
  setTimeout(() => {x.innerHTML= "xét"}, 13250);
  setTimeout(() => {x.innerHTML= "tưởng là"}, 13500);
  setTimeout(() => {x.innerHTML= "mình"}, 13750);
  setTimeout(() => {x.innerHTML= "oai"}, 14000);
  setTimeout(() => {x.innerHTML= "lắm"}, 14250);
  setTimeout(() => {x.innerHTML= "Nhìn"}, 14500);
  setTimeout(() => {x.innerHTML= "vào"}, 14750);
  setTimeout(() => {x.innerHTML= "sự"}, 15000);
  setTimeout(() => {x.innerHTML= "nghiệp"}, 15250);
  setTimeout(() => {x.innerHTML= "anh thèm"}, 15500);
  setTimeout(() => {x.innerHTML= "chảy"}, 15750);
  setTimeout(() => {x.innerHTML= "nước"}, 16000);
  setTimeout(() => {x.innerHTML= "miếng"}, 16250);
  setTimeout(() => {x.innerHTML= "Giống mấy"}, 16500);
  setTimeout(() => {x.innerHTML= "thằng"}, 16750);
  setTimeout(() => {x.innerHTML= "biến"}, 17000);
  setTimeout(() => {x.innerHTML= "thái"}, 17250);
  setTimeout(() => {x.innerHTML= "nó đang"}, 17500);
  setTimeout(() => {x.innerHTML= "rình"}, 17750);
  setTimeout(() => {x.innerHTML= "ai"}, 18000);
  setTimeout(() => {x.innerHTML= "tắm"}, 18250);
  setTimeout(() => {x.innerHTML= "End!"}, 19250);
